In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('SIM_Process_Log.txt', header = None)

In [8]:
df['Robot'] = df[0]
df['Time'] = df[0]
df['SIM'] = df[0]
df['SIM_Count']=''

In [16]:
df

,0,Robot,Time,SIM,SIM_Count
0,Robot_ID:yingyy-07/10/2020 09:07:39-SIM proces...,Robot_ID:yingyy,07/10/2020 09:07:39,SIM processed:P37472778;,1
1,Robot_ID:yingyy-07/10/2020 11:23:02-SIM proces...,Robot_ID:yingyy,07/10/2020 11:23:02,SIM processed:P37498780;,1
2,Robot_ID:yingyy-07/10/2020 11:29:30-SIM proces...,Robot_ID:yingyy,07/10/2020 11:29:30,SIM processed:P37498865;,1
3,Robot_ID:yingyy-07/10/2020 13:27:24-SIM proces...,Robot_ID:yingyy,07/10/2020 13:27:24,SIM processed:P37500703;,1
4,Robot_ID:yingyy-07/10/2020 14:37:03-SIM proces...,Robot_ID:yingyy,07/10/2020 14:37:03,SIM processed:P37501565;,1
...,...,...,...,...,...
236,Robot_ID:yingyy-12/08/2020 22:01:08-SIM proces...,Robot_ID:yingyy,12/08/2020 22:01:08,SIM processed: Errored,0
237,Robot_ID:yingyy-12/08/2020 22:04:13-SIM proces...,Robot_ID:yingyy,12/08/2020 22:04:13,SIM processed: Errored,0
238,Robot_ID:yingyy-12/08/2020 22:07:17-SIM proces...,Robot_ID:yingyy,12/08/2020 22:07:17,SIM processed: Errored,0
239,Robot_ID:yingyy-12/09/2020 12:02:54-SIM proces...,Robot_ID:yingyy,12/09/2020 12:02:54,SIM processed:P42369136;,1
240,Robot_ID:yingyy-12/09/2020 12:45:12-SIM proces...,Robot_ID:yingyy,12/09/2020 12:45:12,SIM processed:P42369686;,1

In [15]:
for index, row in df.iterrows(): 
    row['Robot'] = row[0].strip().split('-')[0].strip()
    row['Time'] = row[0].strip().split('-')[1].strip()
    row['SIM'] = row[0].strip().split('-')[2].strip()
    row['SIM_Count'] = row[0].count(';')

In [18]:
df.to_excel('RPA_Yank&UnYank_2020_DataExtraction.xlsx', index = False)